# Generated by Django 4.2 on 2026-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('firm', 'Firm')], default='moderate', max_length=10),
        ),
    ]
