# Generated by Django 4.2 on 2026-07-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Identity'), (2, 'Property'), (3, 'Video'), (4, 'On-site')])),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=15)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_steps', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'host_verification_steps',
                'ordering': ['level'],
                'unique_together': {('host', 'level')},
            },
        ),
    ]
